### ISSUE TITLE
Please add subgraph support

### ISSUE THREAD

**Issue by gongxiao** [y-takey/atom-mermaid#14]
The atom-mermaid 0.2.0 seems not to support subgraph in graph. The mermaid code like:

```
graph TB
    A[XXXX]

    subgraph XXX XXX
        B1[XXXX XX]
        B2[XXX]
        B3[XXX]
        B1-->B2
        B2-->B3
    end

    A-->B1
```

**Comment by y-takey** [comment]
Thanks for the report.

I tried the mermaid code on mac osx(10.10.5), then it succeeded.

![2015-11-24 10 10 15](https://cloud.githubusercontent.com/assets/1817802/11354939/d1a1dbee-9293-11e5-9b9d-2bf0b0b9a779.png)

I have two questions.
1. ) What is your PC? Windows, Mac, or Linux? (with the version)
2. ) Does the package works on your PC, if the mermaid code is simple?

**Comment by gongxiao** [comment]
I'm sorry about the mistake. My PC is running Windows 7. Today morning, the atom automatically update to 1.2.4. I recied your email and check the problem again. It's very strange to find that everything is OK now. It seems that there is some problem with my PC's configuration. The atom-mermaid package is OK.

**Comment by y-takey** [comment]
I see.  I hope it goes well :)
This issue will close, please reopen if any problem happened.
