### ISSUE TITLE
Support export preview image is better

### ISSUE THREAD

**Issue by Airead** [y-takey/atom-mermaid#17]
Thanks for your atom-mermaid!

**Comment by y-takey** [comment]
Thanks for your request! OK, I will try implement it.

**Comment by y-takey** [comment]
I implemented the export feature. and published the atom package.(to v0.3.1)
Please upgrade your atom-mermaid, then try to export feature. you can see the usage about export feature in [README](https://github.com/y-takey/atom-mermaid/tree/master#export)

Thanks,
