### ISSUE TITLE
Save as png work wrong?

### ISSUE THREAD

**Issue by trickyEdecay** [y-takey/atom-mermaid#19]
when i try to save a mermaid which has nodes with round edges as png. those round edges nodes become black color.How can i fix it?or it's an bug?

**Comment by y-takey** [comment]
Hi, @trickyEdecay, 
Thanks for report. I think it's a bug. Please let me show the your mermaid code, if you don't mind.

**Comment by trickyEdecay** [comment]
graph LR;
  A(Node1)
  C(Node2)

  A--text-->C

**Comment by y-takey** [comment]
Thank you. I was to reproduce the problem. I will take a look.

**Comment by y-takey** [comment]
Hi, @trickyEdecay, 
I've fixed the bug. and published the newer atom package.(to v0.3.2)
Please upgrade your atom-mermaid, then try it.

Thanks,

**Comment by y-takey** [comment]
I close this issue, please reopen if there is problem again.
