### ISSUE TITLE
MermaidView.trigger is deprecated.

### ISSUE THREAD

**Issue by vmuriart** [y-takey/atom-mermaid#2]
Are you trying to dispatch the 'atom-mermaid-preview:html-changed' Atom command with `jQuery::trigger`?
`jQuery::trigger` can no longer emit Atom commands as it will not correctly route
the command to its handlers. Please use `atom.commands.dispatch` instead.
See the docs at https://atom.io/docs/api/latest/CommandRegistry

**Comment by y-takey** [comment]
@vmuriart Thank you. 
I replaced MermaidView.trigger with atom.commands.dispatch .
