### ISSUE TITLE
Save as PNG subgraph fill color is black

### ISSUE THREAD

**Issue by TonyHeflin** [y-takey/atom-mermaid#21]
This appears to be similar to #19. My graph is below.

Thanks for the effort you have put into this package.

graph LR
%% Approval Process ERD

fAP_U_UserID --> tUsr
fAP_U_ApprovalID --> fAP_ID

fAP_Type --> tAT

tMedia --- tAp

subgraph Media table
  tMedia(Media)
end

subgraph User Table
  tUsr(User)
end

subgraph Approval_User Bridge Table
  tAP_U(Approval_User)
  tAP_U --- fAP_U_UserID[User ID]
  tAP_U --- fAP_U_ApprovalID[Approval ID]
end

subgraph ApprovalType Table
  tAT(ApprovalType)
  tAT --- fAT_ID[Approval TYpe Id]
  tAT --- fAT_Name[Name]
  tAT --- fAT_Desc[Description]
end

subgraph Approval Table
  tAp(Approvals)
  tAp --- fAP_ID[ID]
  tAp --- fAP_Name[Name]
  tAp --- fAP_Desc[Description]
  tAp --- fAP_UserId[User ID]
  tAp --- fAP_TaskId[Task ID]
  tAp --- fAP_TaskType[Task Type]
  tAp --- fAP_Status[Status]
  tAp --- fAP_Type[Approval Type]
end

subgraph Approval_User Template Table
  tAP_T(Approval_User)
  tAP_T --- fAP_T_UserID[User ID]
  tAP_T --- fAP_T_Type[Approval Type]
  tAP_T --- fAP_T_Start[Start Date]
  tAP_T --- fAP_T_End[End Date]
  tAP_T --- fAP_T_More[...]
end

**Comment by y-takey** [comment]
Hi, @TonyHeflin 

Thanks for your reportng, and sorry for the delay.
I've fixed the bug. and published the newer atom package.(to v0.3.3)
Please upgrade your atom-mermaid, then try it.

There may be any graph type that does not supported. if so, please tell me.

Thanks,

**Comment by TonyHeflin** [comment]
y-takey,

Looks great, thanks so much for the quick response.

T
