### ISSUE TITLE
Save as PNG misses last few rows of pixels

### ISSUE THREAD

**Issue by ChristopherMeek** [y-takey/atom-mermaid#25]
When right-clicking the preview and selecting "Save as PNG" the exported file does not include the lower hundred or so pixels.

I'll put together an example diagram and post it shortly.

**Comment by ChristopherMeek** [comment]
Ok, so here is an example

```
sequenceDiagram
participant Alice
participant Robert
participant Christopher
participant Louis
participant Alfred
Alice->>Robert: A Random message sent this way
Robert->>Christopher: Message Received
Christopher->>Louis: process message
Louis->>Christopher: message processed and waiting
Note over Christopher: set internal variables and stuff
Christopher->>Alfred: get results list
Christopher->>Robert: send results list
Robert->>Alice: render results list
```

Screen grab of the preview window and exported image attached.

Preview Screenshot
<img width="777" alt="previewscreenshot" src="https://cloud.githubusercontent.com/assets/1965647/14672263/a046e560-06ee-11e6-884d-cb1c326bd2c9.png">

Exported File
![error diag](https://cloud.githubusercontent.com/assets/1965647/14672273/b97747dc-06ee-11e6-8348-f5b97b15cfcb.png)

**Comment by ChristopherMeek** [comment]
Oops, didn;t mean to close with that last comment.

**Comment by ChristopherMeek** [comment]
It seems to be sensitive to the size of the preview window.  If I make the preview window bigger than the images don't get cropped.

**Comment by y-takey** [comment]
Hi @ChristopherMeek,

Thanks for your reporting. I've fixed the bug. and published the newer atom package.(to v0.3.6)
Please upgrade your atom-mermaid, then try it.

Thanks,

**Comment by ChristopherMeek** [comment]
Works for me now!

**Comment by y-takey** [comment]
Thanks!
