### ISSUE TITLE
Save as PNG failure

### ISSUE THREAD

**Issue by ganquan** [y-takey/atom-mermaid#27]
atom-mermaid is a cool package, I really like it. However, When I save the Gantt Diagram Demo to PNG, it just export a black png.

OS: Mac OSX 10.11.4 (15E65)
Atom: 1.7.3
atom-mermaid: latest version

![mermaid_test](https://cloud.githubusercontent.com/assets/252301/15071450/3c772eaa-13be-11e6-877f-77c0e73e5168.png)

**Comment by y-takey** [comment]
Hi @ganquan ,

Thank you for reporting. I've fixed the bug. and published the newer atom package.
Please upgrade your atom-mermaid to v0.3.7, then try it.

Thanks,

**Comment by ganquan** [comment]
Hi @y-takey,

Thank you for fixing. I upgrade  atom-mermaid to v0.3.7, it works well.

Thanks.
