### ISSUE TITLE
markdownとの連携

### ISSUE THREAD

**Issue by baron-tommy** [y-takey/atom-mermaid#30]
1つのmarkdownファイルの中で利用したいです
previewが難しそうですが、、
可能でしたらご検討お願いします。

``` js
console.log('hoge')
```

``` mermaid
graph LR;
    A-->B
```

**Comment by y-takey** [comment]
@BaronTommy さん、ご要望ありがとうございます。

直接の対応ではなく恐縮ですが、下記のpackageで実現できると思います。(使用にはファイルを保存しておかないといけない等、若干の制約がありますが、ほぼ上位互換です)
https://github.com/shd101wyy/markdown-preview-enhanced

ご検討ください。

**Comment by baron-tommy** [comment]
ご連絡ありがとうございます。

質問した後に、下記を見つけてclosedにしました。
https://github.com/shd101wyy/markdown-preview-enhanced

ご提案ありがとうございます。
