### ISSUE TITLE
Add support to save the graphic as SVG 

### ISSUE THREAD

**Issue by xipki** [y-takey/atom-mermaid#31]
Currently the graphic can only be saved as PNG. Do you plan to extend the atom plugin to save it as SVN?

**Comment by y-takey** [comment]
Hi @xipki,

Sorry, I don't have the plan now. why don't you convert PNG to SVG. ( e.g. http://image.online-convert.com/convert-to-svg )

best regards,

**Comment by StefanoCecere** [comment]
if you need a SVG version of the graph, @xipki use http://knsv.github.io/mermaid/live_editor/

@y-takey it would be anyway easy to geenrate the SVG by using mermaid-cli --svg !

**Comment by xipki** [comment]
It is not a good opinion to use online editor for private/enterprise data.
@y-takey By exporting the sequence diagram as PNG and then converting it to SVG you are not able to get the diagram in SVG-qualitiy.

**Comment by y-takey** [comment]
Sorry for the delay.

@StefanoCecere Thank you the advice.

@xipki I implemented feature `save as SVG`, and update atom-mermaid to v2.2.0. would you try it?

**Comment by xipki** [comment]
Thanks. The fix works.

**Comment by y-takey** [comment]
Thank you.
