### ISSUE TITLE
split down zoom level

### ISSUE THREAD

**Issue by nestoru** [y-takey/atom-mermaid#39]
Greetings,

Thanks for this package. Would it be possible to allow adjusting the zoom level? This would be necessary when working with gantt diagrams with using atom split down option. See the picture below:

![screen shot 2017-01-20 at 4 57 10 am](https://cloud.githubusercontent.com/assets/393446/22145005/98abb5bc-decd-11e6-8ba3-fdd91171d50f.png)

Cheers,
- Nestor

**Comment by nestoru** [comment]
My bad, it actually adjusts the zoom pretty well after a first edit:
![screen shot 2017-01-20 at 5 03 50 am](https://cloud.githubusercontent.com/assets/393446/22145082/ece34500-decd-11e6-9ef7-09a33679ca85.png)

This is a non issue. Sorry for the noise.

**Comment by y-takey** [comment]
Hi, not at all, please don't mind.
