### ISSUE TITLE
Preview not picking up classDef default styles

### ISSUE THREAD

**Issue by chrowe** [y-takey/atom-mermaid#41]
Running 3.0.0 on Atom 1.15.0

When I try
```
graph LR;
A
B
classDef default fill:#f9f,stroke:#333,stroke-width:4px;
```
[in the online editor it works](http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFI7CkEKQgpjbGFzc0RlZiBkZWZhdWx0IGZpbGw6I2Y5ZixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6NHB4Ow)

When I do the same in Atom I don't see the styling applied
![screen shot 2017-04-03 at 5 39 14 pm](https://cloud.githubusercontent.com/assets/240115/24633036/7df8439c-1894-11e7-8367-61e53f9c9c32.png)

Applying styles with specific classes works fine.

**Comment by y-takey** [comment]
Hi @chrowe, 

Thanks for your report. I fixed the issue, and upgrade the package (to v3.1.0).

**Comment by chrowe** [comment]
Thanks.
Looks like 55c2d34f7efd52bf2005da1262951d0febed3673 did the trick.

I was able to check for updates in Atom, download the new version, restart Atom and it worked.

**Comment by chrowe** [comment]
![screen shot 2017-04-03 at 9 25 56 pm 1](https://cloud.githubusercontent.com/assets/240115/24638139/327e6aac-18b4-11e7-9252-1c1271afe07c.png)

**Comment by y-takey** [comment]
Thank you for the check!

**Comment by linusnorton** [comment]
I am having the same issue with 3.2.1 using the same example chrowe highlighted. Is there anything I can do to help debug?

Edit: to be fair it doesn't seem to work in the [online editor either](http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFI7CkEKQgpjbGFzc0RlZiBkZWZhdWx0IGZpbGw6I2Y5ZixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6NHB4Ow). Has the format changed?

**Comment by y-takey** [comment]
Hi @linusnorton , Thanks for your report :) 
I think It's a mermaid's issue. https://github.com/knsv/mermaid/issues/582
