### ISSUE TITLE
Not available in Atom 1.18.0

### ISSUE THREAD

**Issue by g1ps** [y-takey/atom-mermaid#42]
The package is not listed in Settings/Packages. Why not? Great shame.

**Comment by g1ps** [comment]
Manual installation does work but the package doesn't. There are no main or context menu entries and no functionality available anywhere else that I can find. I presume it needs updating for the later version of Atom.

**Comment by y-takey** [comment]
Thanks for the report. :)  I was able to reproduce the problem by uninstall and reinstall. i will fix it.

**Comment by g1ps** [comment]
When I next started Atom, the menu items had appeared. A quick test showed that the preview does work, so things now don't appear to be as broken as they seemed.

**Comment by y-takey** [comment]
Thanks, I tried to reproduce the problem just now, but i can't. If same problem appear, please reopen this issue. :)
