### ISSUE TITLE
Preview tool is not rendering

### ISSUE THREAD

**Issue by gregorym** [y-takey/atom-mermaid#43]
I am using Atom 1.20

See screenshot:
![screen shot 2017-09-26 at 6 49 47 pm](https://user-images.githubusercontent.com/245300/30892093-92320ca8-a2eb-11e7-8305-a615394c0641.png)

**Comment by y-takey** [comment]
Hi @gregorym ,

Thanks for the report :)
I tried following environment, but can't reproduce the issue.

```
Atom: 1.20.1
atom-mermaid: 3.1.0
OS: macOS 10.12.6
```

here is tried code:
```
sequenceDiagram
  Alice ->> Bob: Hello Bob, how are you?
  Bob-->>John: How about you John?
  Bob--x Alice: Ia am good thanks!
  Bob-x John: I am good thanks!
  Note right of John: Bob thinks a long<br/>long time, so long<br />that the text does<br/>not fit on a row.

  Bob-->Alice: Checking with Jonhn...
  Alice->John: Yes... John, how are you?
```

Could you try to copy&paset your code to [mermaid-live-editor](https://mermaidjs.github.io/mermaid-live-editor/) ?
if the result don't works fine, could you show me your code?

**Comment by gregorym** [comment]
It works fine in the live editor. Also I do not see any error logs from the dev console.

@y-takey What do you mean show you my code?

**Comment by y-takey** [comment]
To isolate the problem, I tried to check whether there is the problem on your codebase(mermaid markdown) or on the plugin side. it worked fine in the live editor, then your codebase is correct probably.

What is the version of atom-mermaid you are using?

**Comment by gregorym** [comment]
I have the exact same config as yours:
```
Atom: 1.20.1
atom-mermaid: 3.1.0
OS: macOS 10.12.6
```

Here's what I found when I restart Atom with the Dev Tools open:
```
No deserializer found for 
Object
deserializer: "MermaidView"
```

**Comment by y-takey** [comment]
I think there is no problem about the message, because preview tab is not saved(serialize&deserialize) currently.

umm, sorry i have no clue why. Did you try it after uninstall atom-mermaid and reinstall one?

**Comment by gregorym** [comment]
I did. Same behavior :(

**Comment by y-takey** [comment]
Thanks for the try. I have two suggestions.

1. Could you show me your mermaid markdown as a file? There is invisible characters maybe.
2. Could you try with a simple markdown? 
e.g.)
```
sequenceDiagram
  Alice->> Bob: Hi
```

**Comment by zachintosh** [comment]
Hi y-takey,

I am having the same issue. Just wanted to let you know it's not an isolated issue.

I'm on Atom 1.22.0-beta0, and on the most recent version of atom-mermaid. We use mermaid quite a bit where I work, so finding this package was a victory. I'll keep trying to figure out what's wrong.

Thanks!

**Comment by y-takey** [comment]
Hi @zlw11063 ,

Thank you for your comment. :)
I finally succeeded in identifying the cause. so I've fixed the issue, and published a newer version(3.2.1).
Could you try with latest atom-mermaid when you have time?

Thanks!

**Comment by gregorym** [comment]
@y-takey The problem is solved. Thanks for finding the issue and resolving it.

**Comment by y-takey** [comment]
Many thanks!
