### ISSUE TITLE
Unable to export image files

### ISSUE THREAD

**Issue by znorris** [y-takey/atom-mermaid#45]
Atom Version: `1.24.0`
atom-mermaid version: `3.2.1`
Mac OS: `10.13.3`

Exporting images from atom-mermaid result in no files being created. This goes for PNG and SVG.

**Steps to recreate:**
Create a graph.
Open markdown with atom-mermaid.
Right click preview image.
Save As PNG.
Click save.

**Result:**
No PNG file was created.

**Comment by y-takey** [comment]
Hi, @znorris !
Thanks for the report :) I've fixed this issue, and published newer version(3.2.3). Could you retry to export image file.

**Comment by znorris** [comment]
@y-takey the updated version looks good to me. Thank you for such a quick turn around!
