### ISSUE TITLE
styles are hard to read

### ISSUE THREAD

**Issue by vasco3** [y-takey/atom-mermaid#46]
Hi, the dark blue background with the black text is very hard to read. 
Is it possible to change that from the user side?

**Comment by y-takey** [comment]
Hi @vasco3 :)

You can define styles with user stylesheet. 
select [Atom] -> [Stylesheet...] on menu-bar, then define styles like following.

```
# styles.less

.atom-mermaid-preview {
  .node rect,
  .node circle,
  .node polygon {
    fill: #ff0000;
    stroke: #00ff00;
  }
}
```

about overwritable other classes, see https://github.com/y-takey/atom-mermaid/blob/master/styles/atom-mermaid.less

**Comment by vasco3** [comment]
this is perfect, thanks a lot for this plug-in!

**Comment by y-takey** [comment]
I'm happy that I can help you :)
