### ISSUE TITLE
Flowchart preview tool not rendering. 

### ISSUE THREAD

**Issue by monoj** [y-takey/atom-mermaid#48]
The following mermaid code does not render. It gives blank page. 

```
graph TD
    Start --> Stop
```

The following mermaid code renders correctly. 

```
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
```

**Comment by monoj** [comment]
atom-mermaid version: 3.2.3
Atom version: 1.25.0
os: macOS 10.13.3

**Comment by dongho-jung** [comment]
Me too, moreover, my atom-mermaid even don't render above sequenceDiagram mermaid code. It gives me just a blank page.  My environment same as you but os is Windows 10 64bit Home. I really need the mermaid-power what should I do?

When I "Save As PNG" that blank page raise a error like this

```
mermaid-view.coffee:194 Uncaught TypeError: Cannot read property '2' of null
    at HTMLImageElement.<anonymous> (mermaid-view.coffee:194)
(anonymous)	@	mermaid-view.coffee:194
```

**Comment by y-takey** [comment]
Hi @monoj , @0xB4DF4C3D :)
Thanks for your report. (sorry for the delay, @monoj )

I'll fix the issue as soon as possible.

**Comment by y-takey** [comment]
I've fixed this issue, and published newer package@3.2.4.
Cloud you retry after upgrade your package? Maybe you need reinstall(uninstall it, then install it) the package.

**Comment by monoj** [comment]
thanks much @y-takey; it is working now after upgrade.

**Comment by y-takey** [comment]
Thanks for quick response :)
