### ISSUE TITLE
package could not be loaded because they contain native modules that aren't compatible with this version of Atom

### ISSUE THREAD

**Issue by despairblue** [y-takey/atom-mermaid#5]
I'm getting this on linux, though not on mac os

```
Listed below are the incompatible native modules that this package depends on.

contextify@0.1.14
Error message: Module did not self-register.
```

![screenshot from 2015-07-25 03-12-00](https://cloud.githubusercontent.com/assets/927609/8887270/ef61d694-327a-11e5-8255-1d7d873c5806.png)
## Versions
- **Atom:**       1.0.2
- **Atom-Shell:** 0.22.3
- **OS:**         linux 3.14.43-2-lts
- **Misc**
  - apm  1.0.1
  - npm  2.5.1
  - node 0.10.35
  - python 2.7.10
  - git 2.4.5

---

**Comment by y-takey** [comment]
@despairblue Hi,
I think that the problem has occurred due old version of node.js .
Are you able to version up of your node.js?
Please try to re-install the package, if you are able to.

**Comment by despairblue** [comment]
I actually installed iojs 1.5.1 (the one mentioned) reissued `npm install` in the project folder, but to no avail.

**Comment by y-takey** [comment]
Sorry, the latest version of iojs seems to 2.4.
Your iojs it looks like old.

**Comment by despairblue** [comment]
Yeah, because I used the one that atom (see screenshot above) uses :smile: 

Atom does not use the system version of node, iojs or npm, it bundles everything, so there is no reason to use another version. If I'd compile it with 2.4 and atom tries to load it with 1.5.1, what's the point? :smiley:

**Comment by despairblue** [comment]
Just to be sure, I did it again with 2.4. Same result.

**Comment by y-takey** [comment]
Hmm,
Please check atom environment, node path is contained `process.env.PATH`.
( Open atom menu [View → Developer → Toggle Developer Tools], and exec `process.env.PATH` on console ) 
If node path is not contained, add  the following line to your init.coffe. 
( Open atom menu [Atom → Open Your Init Script )

```
process.env.PATH = ["/to/your/node/path", process.env.PATH].join(":")
```

e.g. path is "/Users/xxx/.nvm/v0.12.7/bin"

Sorry for not familiar with atom editor and node.js .

**Comment by despairblue** [comment]
Sorry, I didn't mean to sound harsh. :smiley: 

The path contains `/usr/bin/local`, which is where my node binary resides. I'm not convinced that this is the problem.

I'll come back to this issue when I've got more spare time to debug this. Please keep it open.

Cheers!

**Comment by y-takey** [comment]
Roger!

**Comment by jhartma** [comment]
I have the exact same problem. I am on node 4.0.0 and atom 1.0.11. Atom also knows the node path.

**Comment by y-takey** [comment]
Hi, @jhartma 

Do you also uses the linux?

**Comment by jhartma** [comment]
yep, I'm on Arch Linux

**Comment by jhartma** [comment]
Actually I think it comes down to the contextify module used by mermaid which doesnt compile, and it's not something atom-package related

**Comment by despairblue** [comment]
I also tried `apm rebuild`. It finishes without any errors, but loading
contextify still bails.

**Comment by y-takey** [comment]
Thanks,

contextify seems to be a problem, but it seems to have been left...
https://github.com/atom/atom/issues/8175

**Comment by despairblue** [comment]
fixed with atom 1.0.12

**Comment by y-takey** [comment]
Thank you so much!

**Comment by despairblue** [comment]
Thanks to you for making this package and to the atom folks for upgrading to a more recent iojs version :smiley:
