### ISSUE TITLE
SVG export problem

### ISSUE THREAD

**Issue by juandanielmorcilloregueiro** [y-takey/atom-mermaid#50]
Hi,

congrats on the plugin, it is amazing.

I have a problem to export a flowchart in SVG. When I open the generated SVG file, flowchart appears without text, all the boxes are empty.

Kind regards

**Comment by y-takey** [comment]
Hi @juandanielmorcilloregueiro ,

Sorry for the delay, and thanks your report. I tried to reproduce the issue, but i could't. 
Could you tell me your markdown and your environment(OS, atom and the plugin version)?

**Comment by juandanielmorcilloregueiro** [comment]
Hi @y-takey ,
I give you more details. For example, I generate this diagram:

`graph TD`
`ps((Hello))`
`id0(Assign)`
`ps-->id0`

In the atom viewer, I see the next diagram:

![image](https://user-images.githubusercontent.com/26090303/39130506-827091a6-470d-11e8-8b1b-5c2805059b6a.png)

However, when I export as SVG (doing right clic over the mermaid viewer in Atom), I get the next file (I send you zipped):

[empty.mmd.svg.zip](https://github.com/y-takey/atom-mermaid/files/1938459/empty.mmd.svg.zip)
![image](https://user-images.githubusercontent.com/26090303/39131062-da2340fa-470e-11e8-89ac-8800e8d0d1cf.png)
I use Windows 10 Enterprise 64 bits (Build 10586),  Atom with version 1.26.0 x64 and Atom-mermaid with version 3.2.4.

Thank you and kind regards.

**Comment by y-takey** [comment]
Thank you,
I see the attached file `empty.mmd.svg.zip` , then i get flowchart appears WITH text.
Hmm... Which software do you use to open svg file? for example, if you use Google Chrome then do you see the text?

Kind regards

**Comment by juandanielmorcilloregueiro** [comment]
Hi @y-takey ,

screenshot that I sent you is with Internet Explorer, but I have the same issue with Inkscape:

![image](https://user-images.githubusercontent.com/26090303/39132737-df94c4b0-4712-11e8-85be-f5b1f22d8b75.png)

... but if I open the file with Chrome, I see the text:

![image](https://user-images.githubusercontent.com/26090303/39132826-0b68e008-4713-11e8-8805-2bdb24ec195e.png)

May be a difference between SVG versions or standard?

Kind regards.

**Comment by y-takey** [comment]
Hi @juandanielmorcilloregueiro ,

Thanks for the details :) 
I'll check , but i don't know the details about SVG, so It may take time.

Kind regards.

**Comment by y-takey** [comment]
Hi @juandanielmorcilloregueiro , Sorry for the delay.

I've investigated, the mermaid outputs `foreignObject` tag in the svg. However `foreignObject` isn't supported on IE and MS-Edge. [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject#Browser_compatibility)

Unfortunately, this behavior is mermaid's core feature. so i can't support too.

Kind regards.

**Comment by juandanielmorcilloregueiro** [comment]
Thank you @y-takey , I will use another SVG editor.

Kind regards.
