### ISSUE TITLE
cannot install in atom: depends on mermaid@8.0.0 which hasn't been released yet

### ISSUE THREAD

**Issue by despairblue** [y-takey/atom-mermaid#53]
[This](https://github.com/y-takey/atom-mermaid/blob/c71fc7f573af181b3cb60533ad69c184ea550185/package.json#L20) should reference the rc version otherwise the installation in atom fails because version 8.0.0 does not exist.

<img width="776" alt="screen shot 2018-05-14 at 15 54 53" src="https://user-images.githubusercontent.com/927609/40001751-2b451bc6-578f-11e8-9786-eb1ff6f57b10.png">

**Comment by y-takey** [comment]
sorry, I missed to specify mermaid rc version.
Could you retry after update your atom-mermaid (v3.3.1)?

**Comment by despairblue** [comment]
Thanks, worked nicely 😄
