### ISSUE TITLE
Remove right-click option for mermaid preview

### ISSUE THREAD

**Issue by aar0nr** [y-takey/atom-mermaid#58]
I don't believe that there should be a right-click option to preview mermaid. It seems a little overreaching considering it's global. What do you think?

**Comment by y-takey** [comment]
Hi @aar0nr , thanks for the issue.

I understand your thought, but i wanted to preview mermaid on any file that has no file extension of mermaid(e.g. `.mmd`).
Actually, I don't use atom editor and this package currently. so i have no motivation to improve it.
However i will fix a (little) bug and upgrade dependency packages. Of course welcome a pull request.

Thank you,

**Comment by aar0nr** [comment]
@y-takey No problem, I understand.
