### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by znorris** [y-takey/atom-mermaid#59]
Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
Proxy.writeFileSync (/Users/znorris/.atom/packages/atom-mermaid/node_modules/fs-plus/lib/fs-plus.js:291:24)
MermaidView.writeFile (/Users/znorris/.atom/packages/atom-mermaid/lib/mermaid-view.coffee:292:12)
Image.<anonymous> (/Users/znorris/.atom/packages/atom-mermaid/lib/mermaid-view.coffee:284:19)
```
Atom `1.35.1`

**Comment by y-takey** [comment]
Hi @znorris , thanks for the issue. :)
I couldn't reproduce the issue on my environment(Atom 1.35.1, atom-mermaid: 3.3.1).
Could you tell me steps to reproduce?

**Comment by znorris** [comment]
@y-takey I haven't been able to reproduce the issue again. I'm happy to close the issue and re-open if I can in the future.

**Comment by y-takey** [comment]
Thanks for the reply :)
