### ISSUE TITLE
Latest Atom build not compatible 

### ISSUE THREAD

**Issue by vmuriart** [y-takey/atom-mermaid#6]
Newest ATOM release unable to run mermaid.

**Comment by y-takey** [comment]
Thanks for report.

I fixed the problem. but, other problem was happened, and It is taking time to fix.
sorry, please waiting to be fixed.

**Comment by y-takey** [comment]
@vmuriart 
Sorry I made you wait.
I rebuilt the package for latest atom (v1.0.15), and republish package repository.
Could you please upgrade the package, then check it?

**Comment by vmuriart** [comment]
Sorry for the delay, had a busy week. This is the output im getting when trying to update

```
npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.
```

Same from trying to install after uninstalling it.

**Comment by y-takey** [comment]
Not at all.
Do you use what OS?
If you use Mac OSX and Xcode, please agreeing to the Xcode/iOS license and retry it.

**Comment by vmuriart** [comment]
Windows 8.1, no popups showed up for any licenses on it either.

**Comment by y-takey** [comment]
Sorry, I don't use windows 8.1, follow links Did not helpful to you?
It seems necessary MS Visual Studio.

FYI: 
https://github.com/brianmcd/contextify/issues/120
https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide

**Comment by DSigmund** [comment]
> contextify@0.1.14 install C:\Users\sigmundd\AppData\Local\Temp\apm-install-dir-115830-34188-t8bt93\node_modules\atom-mermaid\node_modules\d3\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

C:\Users\sigmundd\AppData\Local\Temp\apm-install-dir-115830-34188-t8bt93\node_modules\atom-mermaid\node_modules\d3\node_modules\jsdom\node_modules\contextify>node "C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app\apm\bin\\node.exe" "C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\sigmundd\.atom\.apm\.apmrc" "--userconfig" "C:\Users\sigmundd\.atom\.apmrc" "install" "C:\Users\sigmundd\AppData\Local\Temp\d-115830-34188-q00zpj\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

So Same error here i gues

**Comment by sander76** [comment]
Same issue here on windows 7

**Comment by y-takey** [comment]
Sorry for the delay, Could you try the following?
- upgrade npm and node.
- manually install contextify.  
  `
  npm install contextify --msvs_version=2012
  `

**Comment by StefanoCecere** [comment]
atom 1.5.3 osx: installed without any problems!

**Comment by y-takey** [comment]
Thanks for your report!
