### ISSUE TITLE
The classes annotations are invalids in class diagram.

### ISSUE THREAD

**Issue by Andras787** [y-takey/atom-mermaid#68]
Hello,

I wanted to use class annotations in the class diagrams but these could not be shown.

E.g.: <\<interface>\>, <\<enumeration>\>, etc...

![class](https://user-images.githubusercontent.com/14220369/97404378-4abf3b00-18f6-11eb-9c83-6e8c0c459f90.png)

I tested it on the mermaid live editor site and works.
Maybe there is a new standard syntax which has not implemented yet in this plugin.

This mermaid plugin is very useful for us in Atom and the class annotation might be a nice feature for everyone in the future.

Thank you very much!

**Comment by y-takey** [comment]
Hello @Andras787 ,

Thank you for the issue. :)
Updated this plugin and published a newer version(v3.6.0).
But i don't test fully, so please tell me if you find a bug.

**Comment by Andras787** [comment]
Hello @y-takey 

thank you for very fast update! :) 
**It works from now.** 

Maybe only one tiny thing: when I use annotation, the class name and annotation are not in center of class header.
E.g.:

![image](https://user-images.githubusercontent.com/14220369/97412172-7d226580-1901-11eb-9645-fd7fbfe1e51f.png)

Thanks again!

**Comment by y-takey** [comment]
Thanks your quick response.

> when I use annotation, the class name and annotation are not in center of class header.

Hmm, It seems strange. I will fix the issue when i have time.
