### ISSUE TITLE
"Save As" from preview pane doesn't work anymore

### ISSUE THREAD

**Issue by jyutzler** [y-takey/atom-mermaid#74]
### Expected Behavior
When I use the Save As tool, I get a nice PNG of the rendered UML.

### Actual Behavior
The operation fails silently. No files are altered.

### Steps to Reproduce
1. Install Mermaid for Atom v.3.6.0
2. Create a Mermaid class diagram, e.g., https://github.com/jyutzler/geopackage/blob/conceptual-model/spec/conceptual-model/UML/core.uml
3. Toggle Preview in Atom
4. Right-click, "Save as PNG"
5. Choose a file name

This did work at one time but it no longer does. I have tried this on two different machines running different operating systems. It is not clear to me what the problem could be so I am starting here.

**Comment by y-takey** [comment]
Hi @jyutzler , Thanks for the issue :)
I could't reproduce this issue on macOS 11.4. What is your OS?

**Comment by jyutzler** [comment]
macOS 11.3 or Windows 10 Pro (19042.1052). I'm guessing the issue is with some low-level library, but I don't know how to diagnose it.

**Comment by wilwade** [comment]
Same issue.

macOS 11.3 
Atom 1.57.0

**Comment by joshwells** [comment]
Same issue with Atom 1.57.0 and macOS 10.15.7

Issue started with an Atom update.  I have Atom 1.55.0 working for now.

**Comment by y-takey** [comment]
@joshwells Thanks  the detail info. I will try to fix this issue.

**Comment by y-takey** [comment]
fixed this issue, and published atom-mermaid@3.7.1 .

**Comment by joshwells** [comment]
Fix confirmed with Atom@1.58.0 and atom-mermaid@3.7.1.  Thanks so much for taking care of this!
