### ISSUE TITLE
Syntax error in graph

### ISSUE THREAD

**Issue by LucaNun** [y-takey/atom-mermaid#77]
Hello
i used a standard graph from the mermaid website and i only get a syntax error. In vs code everything works.
Syntax error in graph
mermaid version 8.14.0

**Comment by y-takey** [comment]
Hello @LucaNun , thanks for the issue :)
Can you provide sample code that reproduces the problem?

**Comment by LucaNun** [comment]
# mermaid demo

```mermaid
erDiagram

    FollowUser{
        int Creator FK
        int Follower FK
    }

    User{
        int User_ID PK
        varchar255 Vorname
        varchar255 Nachname
        varchar255 Username
        varchar255 E-Mail
        varchar255 Passwort
        varchar255 Hash   
    }


    User ||--|| FollowUser : hat
```
somthing like that

**Comment by LucaNun** [comment]
ok i found the error. i started with 
# mermaid demo
```mermaid
```
I deleted it and now it works

**Comment by y-takey** [comment]
Thanks for providing the sample code!
Unfortunately, this package don't support mermaid syntax in markdown.
if you need, you can use `markdown-preview-enhanced`.
https://atom.io/packages/markdown-preview-enhanced

**Comment by LucaNun** [comment]
Many thanks for the quick help!
