### ISSUE TITLE
Howto Mermaid Preview?

### ISSUE THREAD

**Issue by orschiro** [y-takey/atom-mermaid#9]
Dear @y-takey,

Thank you very much for taking the effort to develop this atom package!

I would love to use the mermaid preview. However, I cannot seem to get it work.

I installed the package on the latest version of Atom on Ubuntu 15.04.

I selected the following code and from the menu launched `Toggle Mermaid Preview` without any rendered result:

```
%% Example code
graph LR
    id1(Start)-->id2(Stop)
    style id1 fill:#f9f,stroke:#333,stroke-width:4px;
    style id2 fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5;
```

![image](https://cloud.githubusercontent.com/assets/170947/10084321/1bca3362-6303-11e5-9769-069e8b4a7461.png)

Am I missing something out which is not covered in the README yet?

Thankfully,

Robert

**Comment by y-takey** [comment]
Dear @orschiro, Thanks

I tried that code on the latest version of **Atom(1.0.18)**, **atom-mermaid(0.1.3)** and Mac OSX(10.10.5). 
but it rendered. 

![2015-09-25 9 23 16](https://cloud.githubusercontent.com/assets/1817802/10090193/6ebb2cfc-6367-11e5-88b7-9602f20659bc.png)

Could you try the following?

1.) more simple code. e.g.)    

``` javascript
  graph LR   
    id1-->id2   
```

2.) uninstall the atom-mermaid and reinstall it.

**Comment by orschiro** [comment]
Dear @y-takey,

Thanks for your help! I followed your advice and reinstalled the package but now it outputs me the following error: 

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [atom-mermaid](https://github.com/y-takey/atom-mermaid) package, v0.1.3

### Stack Trace

Failed to activate the atom-mermaid package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at bindings (/home/orschiro/.atom/packages/atom-mermaid/node_modules/d3/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/orschiro/.atom/packages/atom-mermaid/node_modules/d3/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:428:26)
```

### Commands

```
     -0:04.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:02.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 atom-mermaid:toggle (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-mermaid, v0.1.3
autocomplete-bibtex, v0.6.1
language-todotxt, v0.6.1
markdown-scroll-sync, v0.4.2
typewriter, v0.3.4

# Dev
No dev packages
```

**Comment by y-takey** [comment]
Dear @orschiro,

Did you close preview tab and reboot the atom editor? Please attempt if you didn't.
The issue seems to occur when the old atom-package is running.

**Comment by orschiro** [comment]
Dear @y-takey,

Apologise for the late response. I sense that I face a more general issue with the installation of the package. Upon installation I receive the error that the package cannot self-register. Subsequently, it doesn't show up under installed packages but when searching under Installing new package, it is shown as installed. 

To cover the issue in its entirety, I created the following screencast. 

~ Robert

[mermaid-preview-2015-10-04_09.32.31.mkv | uploaded via ZenHub](https://files.zenhub.io/5610d7a2024bad464a827a93)

**Comment by y-takey** [comment]
Sorry for the delay.  
As your say, It looks like general issue.   

You can get other the mermaid editor(works on cross-platform) if you need.
- [haroopress](http://pad.haroopress.com/)
- [GitBook](https://github.com/GitbookIO/gitbook) (needs [plugin](https://github.com/JozoVilcek/gitbook-plugin-mermaid))

I would be glad if I could help you even just a little.

**Comment by orschiro** [comment]
Dear @y-takey,

Thank you! I will give them a try. :+1: 

~ Robert
